language: node_js
cache: npm
env:
  global:
    - secure: "SgJ5/IrwBIXIKBv5x/GEkTcicCOZYCaGrItwGb+qjli+NcwJe3N3MG+k6rIXAsPZywhFnS1EFcFE+OdMQqmgv2VP4UB4n8ryDDDOlAj9ssZI/7R9bE5o83qlhgtGWFKar74+KQOJV6+QVnKhrw6aXdYPGR69LONlJZww4rUSO480o9CGnvAvt/SOLw8HGiZx9wyjxg2GpvAIpRB+YIpt/1/+Sjdp73mim5Q0JAQDlsrg3/fDA1xJF1lm3ZWC4GfibqHhIS8O63+FfuQDC+jeMGkNW0JoXqze27Ky/Yt8bRvP2LlG7OXNxigA5T+g1oTsMH2QsTmeBGhv6ERE+hsuA98oDYY3nDJa8NexZyxw2OmMNRwxkskYUUz3ZZ9Cb+HyWy8YtS6rVL6RqlXCYdnMH1df4Y30ocO8ggQfgYbFe/IS1uTV1WosB/ChS7w48gNsXEdRO92wHb4i6RNlFabzDWOAtfDp9nNcAwLTHtQG7AqB85IXPSRJtfjVg2meL4b6Pnsszwt0T157BZeg37rRAAoY7qL1WgVXEujbT9O5rUlMAgJ/ptAuTSvBT/FEDx8WSA2bRlV+Yyys9flQTPMe1Z0jMTqeLCyJPuAAkFRx0IBvLvZThMmoKNUtiqEbfuseRQShpi7Oft+nXD24YvTd8pUwgLiwsmm5yI36lLlmZaU="
    - secure: "dnLrWGB++tqMO61yU3nbwNNTp5I+YkdPCmZ6/YXT6ymfwQlrt0qKI48xxMswVA1qYxs6hMEU2+aAmQxVTRryRZIrXG959wXmoOYkaTDTEGh2V/MeHt7hqVRXeCWjq4dVnH6ZzmCVmKFSqHjw+xMwA4xFvlo4sRYFmqTqgepJ02Mx4JN1NkYsec+K0oCtq00Pre2/8Dr1vxE1uReNeC2jrdvzYzkgpox+Dbl9dK9vSKD9cURr70tQH8o9WOyuCJYrMt2rZR+0bDwazlueRkoMT1JAOZ4EubzEu49/r/yN0gREddpcaVl0Xrjs5WuKBij7EHgvUwhp/lAHUu9lFKbfqFU4UfvVOi2v9dflCdepsXOTFGD6o448/jpyyAMKuTexRG0RJZSST3wGHPk/ruxHKxPp6yL6ve4nYbReQwppXbf82ZpY2tP0ApBDjq8LfZYz/fUgESeeUsUK+wRMJt+3yZTaD7NST8KlY2XQDe3RMOX18jiulb6UY/iZd51TxL8AsegdrbyJfAppNVIE4t+jzRHRmeqcSvSysj/ojP49sQwat4YnKUhV9XSTYBjIjasEMt8M74tCCmbbtCgMFVUXzyQP3L9cIe6VMme5eHW+I7DrWALO84QIwor/0AUkem3ytv/PnE92mcFwov+zakGRLoqRK1kFxqZdlNHqvsCKtEg="
before_install:
 - sudo snap install jo
install:
 - npm install
script:
 - gatsby build
node_js:
 - node
after_success:
 - bash travis_build.sh