language: node_js
cache: npm
env:
  global:
    - secure: "ILJqlJkgPylcXO60K71Y7uP2E/N9XwBJ5yRrFBWJUKBukXmyc2rMtCD4EYLENmlcbnwdzqzPz6ottlxI9aADRG5h67ukEfKbUXbaDBL628WhQR9858k5jacnZ6Z8G9vDc4F/wy+E65Ws/ykNE0OT1AWIlrVesd6IkJsCP75KZz6JzN8xDZMeV+oFm60d1yD5lGSpK+vvIGnYxUClrVL49rW6T6Cl3hj0DvPAlQmvq9/b0QglWl7X767dHo82xrvr80na+CezWlXD4Jynv9wsL607ZqgBQErAfi+Kl8mIWorGRtl1Pm5OJCF3mJvI5QjUEdCh5ZDY7uqqtrio3P5pCrv4EfcReYFd8yp433aSEfDg9AP2EID93nHH6k5173DddLyO0qSVFrscJpMPfst9tohWJRip0qINc6K8QqfDKVJsOreua+5t6ibvcbXXxQB2cdEj97byh3wGLLXnKQfZbRST7mGTDqvei6QdxsD5J5bbRcoEQpfqHK+poSak8gxdw5HyaSwd5qc4jp0jt9jFYpalM1txyvTi71imDB+Ol2SC9AHAT4phKo8+iqTLgJpLfhM055U+yGx+HZ/inIfmglVd3Y5HGW4U5mcv/HwEsJ6cYGP67ONx0IC5pUkXELlYQoIozXNowqw/GdGMOJTJ8M1ALjklKR30tX/f12Bsxss="
    - secure: "TnNJlQMJVpN21IiaA2ECpL6FhDju6KOICnOKXG7e5Jc3NlvJPfbFGo3nt2K+yXmJUgVG1OhH0yChAIDZrxyOGYmhHBcMBUYCh3+Mr7aiazQ7277XFUbS1Hm+LXrAY1wFz795CQ1PQ+VsMBaGxswjW/CEBw7FuC17jSt9QHzIcUoRdmGgJ2gluJPbohBP+dd+ecA8zgotVs2m8b4vb2Hcp6zDGhzd1stYFP6OF6AKLSrd7miAOlfItPQEFDfQw9P9Fj412cjD1wYaIMG+yZLCoHXkkWpHhB5zNuji+TSOeXJmztq1+uKUTVGdGJYubZqJ/YJYXS4NFl9TAk9szr0KmYB68fmjv/1Vi4EKOkG9tJt0/9r/hdtrJXcjSE8Eoyy2UTiCZ/wWEN94HEUtns8VNgy9rdSt3SNixEfQjR8g8oDtIsYNau9kt8cBTYpB59cP+z2/bZsAH6TNp1KVTwSrmhT4jSsiVX2RQ25YJm1Jc2bJrHzF6YGO/q6ZnKK99ZQtb+xO/zeFYLq5RoT4z3wB9S1exypG35J1XH04lspvQlO5jBTZBIMtr6Q3TyxEKNdQRADh5jiKDye90ZsqvgQkSn58JEpFQuJjUZNx1o1p9rStSzfpp6iUaDBNNIniKiUt1i8OsE7wr1jEeUg3NzyRGagxYsZGg61Gg/i3h1yiKy0="
before_install:
 - sudo snap install jo
install:
 - npm install
script:
 - gatsby build
node_js:
 - node
after_success:
 - bash travis_build.sh